# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb126b9f3f6897781a5ea4bb22a662377c18df66744fc4a70f0cccd6ca8a827b7597ffd88376de3e6dc671f7271005095efa29600886ff4b6a020ede8b5a9e09

test:
  secret_key_base: 4d4e6132008b8ceeccfce78bca7611c0ee9254e4ee6b0828f8c96fb9d2f10fb9fce55e4db885e8bf4e5fef0219180e45bf83da8383ca35f67fb422b8a24d77d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
